// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mydata.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Data1                string   `protobuf:"bytes,1,opt,name=data1" json:"data1,omitempty"`
	Data2                string   `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_mydata_a1d4b565749283c5, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetData1() string {
	if m != nil {
		return m.Data1
	}
	return ""
}

func (m *Data) GetData2() string {
	if m != nil {
		return m.Data2
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "proto.Data")
}

func init() { proto.RegisterFile("mydata.proto", fileDescriptor_mydata_a1d4b565749283c5) }

var fileDescriptor_mydata_a1d4b565749283c5 = []byte{
	// 78 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xad, 0x4c, 0x49,
	0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x46, 0x5c, 0x2c,
	0x2e, 0x89, 0x25, 0x89, 0x42, 0x22, 0x5c, 0xac, 0x20, 0x49, 0x43, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x08, 0x07, 0x26, 0x6a, 0x24, 0xc1, 0x84, 0x10, 0x35, 0x4a, 0x62, 0x03, 0x6b, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x44, 0x7a, 0x51, 0x21, 0x51, 0x00, 0x00, 0x00,
}
